### ISSUE TITLE
Move to jekyll (gh-pages style)

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs.github.io#1]
That should enable us to only push a change to README.md which then triggers an update.

**Comment by holgerd77** [comment]
@axic I would like to take on this, and then - as a second, separate step - also update the website content and remove outdated stuff.

Would start this by going to "Settings" and then select "Choose a theme and migrate your content". Probably this will integrate better into GitHub then setting Jekyll up manually from scratch. Not sure what will exactly happen though. As a backup measure I would clone the repo locally and - if something goes wrong - post-insert the existing content (shouldn't be that much of a task in case since content/text quantity is pretty limited).

Would this be ok for procedure?

**Comment by axic** [comment]
It is already done the way you describe it.

The current problem is that every time the Github wizard is used to update it, the contents of `README.md` are pasted there, which is a manual process.

The idea here is to automate this.

**Comment by axic** [comment]
Okay I may have clicked the button now out of curiosity and it applied changes without a final confirmation. We can drop the last commit by force pushing master to go back.

**Comment by axic** [comment]
It seems you are correct, they have changed it. We can symlink `README.md` to `index.md` (or the other way around) and have this done.

**Comment by axic** [comment]
It seems to be working with symlinking properly. Sorry for doing it :(

Do you want to update the contents of README to match the current situation?

**Comment by holgerd77** [comment]
No problem, cool to have this updated now. :octocat: 😄 

Can do (README), but will do in the coming days as a separate PR, would also like to do some layout enhancements/structural improvements and maybe also integrate some [GitHub metadata](https://help.github.com/articles/repository-metadata-on-github-pages/).
