### ISSUE TITLE
Update docs website

### ISSUE THREAD

**Issue by ScottyPoi** [ethereumjs/ethereumjs.github.io#9]
This has not been updated for  2 years.  

- [ ] Links need updating
- [ ] New packages need links
- [ ] Update examples and use-case instructions
- [ ] Include up-to-date docs and install guides
- [ ] Could use a snazzier UI

**Comment by holgerd77** [comment]
Also made another comment on this "somewhere else" [TM] 😋 (with tldr; throw away at some point eventually respectively redo very differently), just a note that it nevertheless very much makes sense to do this as a 2-step-process and in a first round just do a all-what-is-necessary update so that this somewhat aligns back with the recent state without too much effort.
